DROP VIEW DEPARTMENT_STAFF;

CREATE VIEW DEPARTMENT_STAFF(DName,SName,Job)
AS 
(SELECT DEPARTMENT.Name AS DName, S1.Name 
AS SNAME,S1.Job AS Job
FROM STAFF S1 JOIN DEPARTMENT
ON(DEPARTMENT.Manager=S1.StaffId))
UNION
(SELECT DEPARTMENT.Name AS DName, S2.Name 
AS SNAME,S2.Job AS Job
FROM STAFF S1 JOIN STAFF S2 ON(S1.StaffId=S2.Supervisor)
JOIN DEPARTMENT ON(DEPARTMENT.Manager=S1.StaffId));
