SELECT DISTINCT CUSTOMER.Name AS N
FROM CUSTOMER JOIN STREAM JOIN MOVIE 
ON (CUSTOMER.CustomerId=STREAM.CustomerId 
AND MOVIE.MovieId=STREAM.MovieId)         
WHERE HOUR(STREAM.StreamDate)>=20
AND MOVIE.Duration>=180
ORDER BY N;
