SELECT Title, StreamDate,Charge
FROM STREAM JOIN MOVIE JOIN MOVIE_GENRE JOIN GENRE
ON(STREAM.MovieId=MOVIE.MovieId 
AND MOVIE.MovieId=MOVIE_GENRE.MovieId
AND MOVIE_GENRE.GenreId=GENRE.GenreId)
WHERE YEAR(StreamDate)=2017 AND MONTH(StreamDate)=12
AND Label='Thriller'
ORDER BY Title, StreamDate DESC;
