SELECT Title, COUNT(StreamId) AS N
FROM MOVIE JOIN STREAM JOIN CUSTOMER JOIN COUNTRY JOIN REGION
ON(MOVIE.MovieId=STREAM.MovieId 
AND STREAM.CustomerId=CUSTOMER.CustomerId
AND CUSTOMER.Country=COUNTRY.Name
AND COUNTRY.RegionId=REGION.RegionId)
WHERE REGION.Name='Asia'
GROUP BY Title
ORDER BY N DESC,Title
LIMIT 20;
