UPDATE STREAM
SET Charge=0
WHERE CustomerId NOT IN(
SELECT CustomerId
FROM CUSTOMER 
JOIN COUNTRY ON(CUSTOMER.Country=COUNTRY.Name)
JOIN REGION ON(COUNTRY.RegionId=REGION.RegionId)
WHERE REGION.Name='America')
AND MovieId IN(
SELECT MOVIE.MovieId
FROM MOVIE JOIN MOVIE_GENRE JOIN GENRE
ON(MOVIE.MovieId=MOVIE_GENRE.MovieId
AND MOVIE_GENRE.GenreId=GENRE.GenreId)
WHERE Duration<=120 AND Label='Biography')
;
