DELETE MOVIE_ACTOR 
FROM MOVIE_ACTOR
WHERE MOVIE_ACTOR.MovieId IN(
SELECT MOVIE_GENRE.MovieId
FROM MOVIE_GENRE NATURAL JOIN GENRE
WHERE Label='Action')
AND MOVIE_ACTOR.MovieId IN(
SELECT MOVIE.MovieId
FROM STREAM RIGHT JOIN MOVIE ON(STREAM.MovieId=MOVIE.MovieId)
GROUP BY MOVIE.MovieId
HAVING COUNT(StreamId)=0);
