DROP VIEW REGION_DATA;

CREATE VIEW REGION_DATA(Name, Manager, Countries, Customers)
AS
SELECT REGION.Name, STAFF.Name AS Maneger, 
COUNT(DISTINCT COUNTRY.Name) AS Countries,
SUM(CASE WHEN CUSTOMER.Country=COUNTRY.Name AND 
COUNTRY.RegionId=REGION.RegionId THEN 1 ELSE 0 END) AS Customers
FROM CUSTOMER,REGION
JOIN COUNTRY ON(REGION.RegionId=COUNTRY.RegionId)
JOIN STAFF ON(REGION.RegionManager=STAFF.StaffId)
GROUP BY REGION.Name,Maneger
;
