SELECT COUNTRY.Name, GENRE.Label,
SUM(CASE WHEN MOVIE.MovieId=STREAM.MovieId THEN 1 ELSE 0 END)
AS N

FROM STREAM JOIN CUSTOMER 
ON(CUSTOMER.CustomerId=STREAM.CustomerId)
RIGHT JOIN COUNTRY ON(CUSTOMER.Country=COUNTRY.Name),

GENRE 
JOIN MOVIE_GENRE ON(GENRE.GenreId=MOVIE_GENRE.GenreId)
JOIN MOVIE ON(MOVIE.MovieId=MOVIE_GENRE.MovieId)

WHERE COUNTRY.RegionId=6

GROUP BY COUNTRY.Name, GENRE.Label
ORDER BY COUNTRY.Name, GENRE.Label;
