/*--FICHA 11----*/
/* EX 1 */
SELECT CUSTOMER.Name, COUNT(StreamId) AS N, SUM(Charge)
FROM CUSTOMER LEFT JOIN STREAM 
ON(CUSTOMER.CustomerId=STREAM.CustomerId)
WHERE Country='India'
GROUP BY Name
HAVING N<=5;

/* EX 2 */
SELECT Title, StreamDate,Charge
FROM STREAM JOIN MOVIE JOIN MOVIE_GENRE JOIN GENRE
ON(STREAM.MovieId=MOVIE.MovieId 
AND MOVIE.MovieId=MOVIE_GENRE.MovieId
AND MOVIE_GENRE.GenreId=GENRE.GenreId)
WHERE YEAR(StreamDate)=2017 AND MONTH(StreamDate)=12
AND Label='Thriller'
ORDER BY Title, StreamDate DESC;

/* EX 3 */
SELECT DISTINCT Title
FROM MOVIE JOIN MOVIE_GENRE JOIN GENRE
ON(MOVIE.MovieId=MOVIE_GENRE.MovieId
AND MOVIE_GENRE.GenreId=GENRE.GenreId)
WHERE MOVIE.MovieId IN(
SELECT MovieId 
FROM MOVIE_GENRE NATURAL JOIN GENRE
WHERE Label='Action' )
AND MOVIE.MovieId IN(
SELECT MovieId 
FROM MOVIE_GENRE NATURAL JOIN GENRE
WHERE Label='Comedy')
ORDER BY Title;

/* EX 4 */
SELECT Title, COUNT(StreamId) AS N
FROM MOVIE JOIN STREAM JOIN CUSTOMER JOIN COUNTRY JOIN REGION
ON(MOVIE.MovieId=STREAM.MovieId 
AND STREAM.CustomerId=CUSTOMER.CustomerId
AND CUSTOMER.Country=COUNTRY.Name
AND COUNTRY.RegionId=REGION.RegionId)
WHERE REGION.Name='Asia'
GROUP BY Title
ORDER BY N DESC,Title
LIMIT 20;

/* EX 5 */
UPDATE STREAM
SET Charge=0
WHERE CustomerId NOT IN(
SELECT CustomerId
FROM CUSTOMER 
JOIN COUNTRY ON(CUSTOMER.Country=COUNTRY.Name)
JOIN REGION ON(COUNTRY.RegionId=REGION.RegionId)
WHERE REGION.Name='America')
AND MovieId IN(
SELECT MOVIE.MovieId
FROM MOVIE JOIN MOVIE_GENRE JOIN GENRE
ON(MOVIE.MovieId=MOVIE_GENRE.MovieId
AND MOVIE_GENRE.GenreId=GENRE.GenreId)
WHERE Duration<=120 AND Label='Biography')
;

/* EX 6 */
DELETE MOVIE_ACTOR 
FROM MOVIE_ACTOR
WHERE MOVIE_ACTOR.MovieId IN(
SELECT MOVIE_GENRE.MovieId
FROM MOVIE_GENRE NATURAL JOIN GENRE
WHERE Label='Action')
AND MOVIE_ACTOR.MovieId IN(
SELECT MOVIE.MovieId
FROM STREAM RIGHT JOIN MOVIE ON(STREAM.MovieId=MOVIE.MovieId)
GROUP BY MOVIE.MovieId
HAVING COUNT(StreamId)=0);

/* EX 7 */
DROP VIEW REGION_DATA;
CREATE VIEW REGION_DATA(Name, Manager, Countries, Customers)
AS

SELECT REGION.Name, STAFF.Name AS Maneger, 
COUNT(DISTINCT COUNTRY.Name) AS Countries,
SUM(CASE WHEN CUSTOMER.Country=COUNTRY.Name AND 
COUNTRY.RegionId=REGION.RegionId THEN 1 ELSE 0 END) AS Customers
FROM CUSTOMER,REGION
JOIN COUNTRY ON(REGION.RegionId=COUNTRY.RegionId)
JOIN STAFF ON(REGION.RegionManager=STAFF.StaffId)
GROUP BY REGION.Name,Maneger
;

/* EX 8 */
SELECT S1.Name AS A1, S2.Name AS A2, 
COUNT(DISTINCT MOVIE.MovieId) AS N, 
COUNT(STREAM.StreamId) AS M

FROM ACTOR S1 JOIN ACTOR S2 
JOIN MOVIE_ACTOR S3 JOIN MOVIE_ACTOR S4
ON(S1.ActorId=S3.ActorId 
AND S2.ActorId=S4.ActorId ) 
RIGHT JOIN MOVIE ON(MOVIE.MovieId=S3.MovieId 
AND MOVIE.MovieId=S4.MovieId )
LEFT JOIN STREAM ON(MOVIE.MovieId=STREAM.MovieId)


WHERE S3.MovieId=S4.MovieId AND S1.Name!=S2.Name
GROUP BY A1,A2
HAVING M>=40 AND A1<A2
ORDER BY M DESC, N DESC, A1,A2;

/* EX 9 */
SELECT COUNTRY.Name, GENRE.Label,
SUM(CASE WHEN MOVIE.MovieId=STREAM.MovieId THEN 1 ELSE 0 END)
AS N

FROM STREAM JOIN CUSTOMER 
ON(CUSTOMER.CustomerId=STREAM.CustomerId)
RIGHT JOIN COUNTRY ON(CUSTOMER.Country=COUNTRY.Name),

GENRE 
JOIN MOVIE_GENRE ON(GENRE.GenreId=MOVIE_GENRE.GenreId)
JOIN MOVIE ON(MOVIE.MovieId=MOVIE_GENRE.MovieId)

WHERE COUNTRY.RegionId=6

GROUP BY COUNTRY.Name, GENRE.Label
ORDER BY COUNTRY.Name, GENRE.Label;

/* EX 10 */
DROP FUNCTION IF EXISTS bonus;
DELIMITER $

CREATE FUNCTION bonus(staff_id INT, year INT)
RETURNS INT
BEGIN
  DECLARE value INT;
  DECLARE n INT;
  DECLARE s INT;
  DECLARE r INT;
  
  SELECT COUNT(STREAM.StreamId) INTO n
  FROM STREAM 
  WHERE MONTH(StreamDate)=12
  AND YEAR(StreamDate)= year 
  GROUP BY MONTH(StreamDate);
  
  SELECT COUNT(S1.StaffId) INTO s
  FROM STAFF S1 
  RIGHT JOIN STAFF S2 ON(S1.Supervisor=S2.StaffId)
  WHERE S2.StaffId=staff_id
  GROUP BY S2.StaffId;
  
  SELECT COUNT(REGION.RegionId) INTO r
  FROM REGION 
  RIGHT JOIN STAFF ON(REGION.RegionManager=STAFF.StaffId)
  WHERE STAFF.StaffId=staff_id
  GROUP BY STAFF.StaffId;
  
  SET value = n * ( s + r + 1 );
  
  IF value < 300 THEN
	SET value = 300;
  END IF;
  
  IF value > 2000 THEN
	SET value = 2000;
  END IF;
  
  RETURN value;
END$

DELIMITER ;














