package defpackage;
/* renamed from: TestED248  reason: default package */
/* loaded from: TestED248.class */
public class TestED248 {
    public static void main(String[] strArr) {
        IntSet booleanArrayIntSet = new BooleanArrayIntSet(1001);
        BooleanArrayIntSet booleanArrayIntSet2 = new BooleanArrayIntSet(1001);
        new BooleanArrayIntSet(1001);
        IntSet booleanArrayIntSet3 = new BooleanArrayIntSet(1001);
        BooleanArrayIntSet booleanArrayIntSet4 = new BooleanArrayIntSet(1001);
        new BooleanArrayIntSet(1001);
        new BooleanArrayIntSet(1001);
        System.out.println(booleanArrayIntSet.size());
        System.out.println(booleanArrayIntSet.add(42));
        System.out.println(booleanArrayIntSet.size());
        System.out.println(booleanArrayIntSet.add(42));
        System.out.println(booleanArrayIntSet.add(21));
        System.out.println(booleanArrayIntSet.add(10));
        System.out.println(booleanArrayIntSet.size());
        System.out.println(booleanArrayIntSet.contains(10));
        System.out.println(booleanArrayIntSet.contains(21));
        System.out.println(booleanArrayIntSet.contains(42));
        System.out.println(booleanArrayIntSet.contains(9));
        System.out.println(booleanArrayIntSet.remove(42));
        System.out.println(booleanArrayIntSet.size());
        System.out.println(booleanArrayIntSet.contains(10));
        System.out.println(booleanArrayIntSet.contains(21));
        System.out.println(booleanArrayIntSet.contains(42));
        System.out.println(booleanArrayIntSet.remove(21));
        System.out.println(booleanArrayIntSet.remove(21));
        System.out.println(booleanArrayIntSet.size());
        System.out.println(booleanArrayIntSet.contains(10));
        System.out.println(booleanArrayIntSet.contains(21));
        System.out.println(booleanArrayIntSet.contains(42));
        System.out.println(booleanArrayIntSet.remove(10));
        System.out.println(booleanArrayIntSet.remove(10));
        System.out.println(booleanArrayIntSet.size());
        System.out.println(booleanArrayIntSet.contains(10));
        System.out.println(booleanArrayIntSet.contains(21));
        System.out.println(booleanArrayIntSet.contains(42));
        System.out.println(booleanArrayIntSet.add(1));
        System.out.println(booleanArrayIntSet.add(2));
        booleanArrayIntSet.clear();
        System.out.println(booleanArrayIntSet.contains(1));
        System.out.println(booleanArrayIntSet.contains(2));
        System.out.println(booleanArrayIntSet.size());
        System.out.println(booleanArrayIntSet.equals((IntSet) booleanArrayIntSet2));
        System.out.println(booleanArrayIntSet.add(1000));
        System.out.println(booleanArrayIntSet.equals((IntSet) booleanArrayIntSet2));
        System.out.println(booleanArrayIntSet2.add(1000));
        System.out.println(booleanArrayIntSet.equals((IntSet) booleanArrayIntSet2));
        System.out.println(booleanArrayIntSet.add(500));
        System.out.println(booleanArrayIntSet2.equals(booleanArrayIntSet));
        System.out.println(booleanArrayIntSet2.add(500));
        System.out.println(booleanArrayIntSet2.equals(booleanArrayIntSet));
        IntSet intersection = booleanArrayIntSet.intersection(booleanArrayIntSet2);
        System.out.println(intersection.equals(booleanArrayIntSet));
        System.out.println(intersection.equals((IntSet) booleanArrayIntSet2));
        System.out.println(booleanArrayIntSet3.add(11));
        System.out.println(booleanArrayIntSet3.add(12));
        System.out.println(booleanArrayIntSet3.add(13));
        System.out.println(booleanArrayIntSet3.add(14));
        System.out.println(booleanArrayIntSet3.add(15));
        System.out.println(booleanArrayIntSet3.add(16));
        System.out.println(booleanArrayIntSet3.add(17));
        System.out.println(booleanArrayIntSet4.add(11));
        System.out.println(booleanArrayIntSet4.add(2));
        System.out.println(booleanArrayIntSet4.add(13));
        System.out.println(booleanArrayIntSet4.add(4));
        System.out.println(booleanArrayIntSet4.add(15));
        System.out.println(booleanArrayIntSet4.add(6));
        System.out.println(booleanArrayIntSet4.add(17));
        System.out.println(booleanArrayIntSet3.intersection(booleanArrayIntSet4).size());
        booleanArrayIntSet4.clear();
        IntSet intersection2 = booleanArrayIntSet3.intersection(booleanArrayIntSet4);
        System.out.println(intersection2.size());
        System.out.println(intersection2.intersection(booleanArrayIntSet3).size());
    }
}
