SELECT MOVIE.Title, ACTOR.Name 
FROM ACTOR JOIN MOVIE_ACTOR JOIN MOVIE
ON(ACTOR.ActorId=MOVIE_ACTOR.ActorId AND MOVIE_ACTOR.MovieId=MOVIE.MovieId)
WHERE MOVIE.MovieId IN(
SELECT MOVIE_ACTOR.MovieId 
FROM MOVIE_ACTOR NATURAL JOIN ACTOR
WHERE ACTOR.Name='Johnny Depp') AND ACTOR.Name!='Johnny Depp'
ORDER BY MOVIE.Title, ACTOR.Name;
