UPDATE STREAM 
JOIN CUSTOMER JOIN COUNTRY 
JOIN REGION JOIN MOVIE 
JOIN MOVIE_GENRE JOIN GENRE
ON(STREAM.CustomerId=CUSTOMER.CustomerId
AND CUSTOMER.Country=COUNTRY.Name
AND COUNTRY.RegionId=REGION.RegionId
AND STREAM.MovieId=MOVIE.MovieId
AND MOVIE.MovieId=MOVIE_GENRE.MovieId
AND GENRE.GenreId=MOVIE_GENRE.GenreId)
SET STREAM.Charge = 4.5
WHERE REGION.Name!='Africa' 
AND MOVIE.Year<1985 AND GENRE.Label='Sci-Fi';
