SELECT MOVIE.Title, REGION.Name, 
SUM(CASE WHEN STREAM.MovieId=MOVIE.MovieId then 1 else 0 end) AS N

FROM MOVIE, STREAM 
JOIN CUSTOMER JOIN COUNTRY 
JOIN REGION
ON( STREAM.CustomerId=CUSTOMER.CustomerId
AND CUSTOMER.Country=COUNTRY.Name
AND COUNTRY.RegionId=REGION.RegionId)

WHERE MOVIE.Title LIKE '%war%'

GROUP BY MOVIE.Title, REGION.Name
ORDER BY MOVIE.Title,REGION.Name;
