DELETE STREAM 

FROM STREAM JOIN CUSTOMER JOIN MOVIE 
JOIN MOVIE_GENRE JOIN GENRE
ON(STREAM.CustomerId=CUSTOMER.CustomerId
AND STREAM.MovieId=MOVIE.MovieId
AND STREAM.MovieId=MOVIE_GENRE.MovieId
AND MOVIE_GENRE.GenreId=GENRE.GenreId)

WHERE (MOVIE.Duration<=120 AND  GENRE.Label='Biography')
AND CUSTOMER.CustomerId NOT IN
(SELECT CUSTOMER.CustomerId
FROM CUSTOMER JOIN COUNTRY JOIN REGION
ON(CUSTOMER.Country=COUNTRY.Name
AND COUNTRY.RegionId=REGION.RegionId)
WHERE REGION.Name='America');
