SELECT GENRE.Label, REGION.Name, 
COUNT(*)

FROM (GENRE JOIN REGION) LEFT JOIN 
(MOVIE_GENRE 
NATURAL JOIN MOVIE
NATURAL JOIN STREAM 
NATURAL JOIN CUSTOMER 
JOIN COUNTRY ON(CUSTOMER.Country=COUNTRY.Name))
USING (RegionId, GenreId)

GROUP BY GENRE.Label, REGION.Name
ORDER BY GENRE.Label, REGION.Name;
