DELETE MOVIE_ACTOR 
FROM MOVIE_ACTOR JOIN ACTOR JOIN MOVIE_GENRE JOIN GENRE
ON(MOVIE_ACTOR.ActorId=ACTOR.ActorId AND
MOVIE_ACTOR.MovieId=MOVIE_GENRE.MovieId AND
MOVIE_GENRE.GenreId=GENRE.GenreId)
WHERE Name='Tom Cruise' AND Label='Action';
