UPDATE STREAM JOIN MOVIE JOIN CUSTOMER JOIN COUNTRY JOIN REGION
ON(STREAM.MovieId=MOVIE.MovieId AND STREAM.CustomerId=CUSTOMER.CustomerId
AND CUSTOMER.Country=COUNTRY.Name AND COUNTRY.RegionId=REGION.RegionId)
SET STREAM.Charge = STREAM.Charge + 1.5
WHERE MOVIE.Duration>=180 AND REGION.Name='Europe';
