SELECT ACTOR.Name, COUNT(*) AS N
FROM ACTOR JOIN MOVIE_ACTOR JOIN MOVIE
ON(ACTOR.ActorId=MOVIE_ACTOR.ActorId AND MOVIE_ACTOR.MovieId=MOVIE.MovieId)
GROUP BY ACTOR.Name
HAVING N>=15
ORDER BY N DESC,ACTOR.Name;
