/*--FICHA 7----*/
/* EX 1 */
SELECT Name 
FROM CUSTOMER LEFT JOIN STREAM 
ON(CUSTOMER.CustomerId=STREAM.CustomerId)
WHERE (StreamId IS NULL AND Country='China');

/* EX 2 */
SELECT Country,COUNT(*) AS N
FROM  STREAM RIGHT JOIN CUSTOMER
ON(STREAM.CustomerId=CUSTOMER.CustomerId)
WHERE StreamId IS NULL 
GROUP BY Country;

/* EX 3 */
SELECT Title,COUNT(StreamId) AS N
FROM MOVIE LEFT OUTER JOIN STREAM
USING(MovieId)
WHERE Year=2015 
GROUP BY Title
HAVING N<=5
ORDER BY Title;

/* EX 4 */
SELECT S1.Name AS NA,COUNT(S2.StaffId) AS N
FROM STAFF S1 LEFT JOIN STAFF S2
ON(S1.StaffId=S2.Supervisor)
GROUP BY NA
ORDER BY N DESC, NA;

/* EX 5 */
DELETE STREAM 
FROM CUSTOMER NATURAL JOIN STREAM  
WHERE Country='China' AND Charge<=5.5;

/* EX 6 */
DELETE MOVIE_ACTOR 
FROM MOVIE_ACTOR JOIN ACTOR JOIN MOVIE_GENRE JOIN GENRE
ON(MOVIE_ACTOR.ActorId=ACTOR.ActorId AND
MOVIE_ACTOR.MovieId=MOVIE_GENRE.MovieId AND
MOVIE_GENRE.GenreId=GENRE.GenreId)
WHERE Name='Tom Cruise' AND Label='Action';

/* EX 7 */
UPDATE CUSTOMER 
SET Active = FALSE 
WHERE Country= 'China' AND CustomerId NOT IN
(SELECT CustomerId FROM STREAM);

/* EX 8 */
UPDATE STREAM JOIN MOVIE JOIN CUSTOMER JOIN COUNTRY JOIN REGION
ON(STREAM.MovieId=MOVIE.MovieId AND STREAM.CustomerId=CUSTOMER.CustomerId
AND CUSTOMER.Country=COUNTRY.Name AND COUNTRY.RegionId=REGION.RegionId)
SET STREAM.Charge = STREAM.Charge + 1.5
WHERE MOVIE.Duration>=180 AND REGION.Name='Europe';

/* EX 9 */
SELECT ACTOR.Name, COUNT(*) AS N
FROM ACTOR JOIN MOVIE_ACTOR JOIN MOVIE
ON(ACTOR.ActorId=MOVIE_ACTOR.ActorId AND MOVIE_ACTOR.MovieId=MOVIE.MovieId)
GROUP BY ACTOR.Name
HAVING N>=15
ORDER BY N DESC,ACTOR.Name;

/* EX 10 */
SELECT MOVIE.Title, ACTOR.Name 
FROM ACTOR JOIN MOVIE_ACTOR JOIN MOVIE
ON(ACTOR.ActorId=MOVIE_ACTOR.ActorId AND MOVIE_ACTOR.MovieId=MOVIE.MovieId)
WHERE MOVIE.MovieId IN(
SELECT MOVIE_ACTOR.MovieId 
FROM MOVIE_ACTOR NATURAL JOIN ACTOR
WHERE ACTOR.Name='Johnny Depp') AND ACTOR.Name!='Johnny Depp'
ORDER BY MOVIE.Title, ACTOR.Name;

/* EX 11 */
SELECT S1.Name AS A1, S2.Name AS A2, COUNT(*) AS N
FROM ACTOR S1 JOIN ACTOR S2 JOIN MOVIE_ACTOR S3 JOIN MOVIE_ACTOR S4
ON(S1.ActorId=S3.ActorId AND S2.ActorId=S4.ActorId)
WHERE S3.MovieId=S4.MovieId AND S1.Name!=S2.Name
GROUP BY A1,A2
HAVING N>=4 AND A1<A2
ORDER BY N DESC, A1,A2;

/* EX 12 */
UPDATE STREAM 
JOIN CUSTOMER JOIN COUNTRY 
JOIN REGION JOIN MOVIE 
JOIN MOVIE_GENRE JOIN GENRE
ON(STREAM.CustomerId=CUSTOMER.CustomerId
AND CUSTOMER.Country=COUNTRY.Name
AND COUNTRY.RegionId=REGION.RegionId
AND STREAM.MovieId=MOVIE.MovieId
AND MOVIE.MovieId=MOVIE_GENRE.MovieId
AND GENRE.GenreId=MOVIE_GENRE.GenreId)
SET STREAM.Charge = 4.5
WHERE REGION.Name!='Africa' 
AND MOVIE.Year<1985 AND GENRE.Label='Sci-Fi';

/* EX 13 */
SELECT STREAM.StreamDate, MOVIE.Title AS N, 
CUSTOMER.Name, CUSTOMER.Country
FROM STREAM JOIN MOVIE 
JOIN CUSTOMER JOIN MOVIE_ACTOR 
JOIN ACTOR
ON(CUSTOMER.CustomerId=STREAM.CustomerId 
AND MOVIE.MovieId=STREAM.MovieId 
AND MOVIE.MovieId=MOVIE_ACTOR.MovieId
AND ACTOR.ActorId=MOVIE_ACTOR.ActorId)
WHERE CUSTOMER.Country!='China' 
AND ACTOR.Name='Johnny Depp'
AND MOVIE.MovieId NOT IN(
SELECT MOVIE.MovieId
FROM ACTOR JOIN MOVIE_ACTOR JOIN MOVIE
ON( MOVIE.MovieId=MOVIE_ACTOR.MovieId
AND ACTOR.ActorId=MOVIE_ACTOR.ActorId)
WHERE ACTOR.Name='Helena Bonham Carter'
)
ORDER BY STREAM.StreamDate DESC
LIMIT 15;

/* EX 14 */
SELECT MOVIE.Title, REGION.Name, 
SUM(CASE WHEN STREAM.MovieId=MOVIE.MovieId then 1 else 0 end) AS N
FROM MOVIE, STREAM 
JOIN CUSTOMER JOIN COUNTRY 
JOIN REGION
ON( STREAM.CustomerId=CUSTOMER.CustomerId
AND CUSTOMER.Country=COUNTRY.Name
AND COUNTRY.RegionId=REGION.RegionId)
WHERE MOVIE.Title LIKE '%war%'
GROUP BY MOVIE.Title, REGION.Name
ORDER BY MOVIE.Title,REGION.Name;

/* EX 15 */
DELETE STREAM 
FROM STREAM JOIN CUSTOMER JOIN MOVIE 
JOIN MOVIE_GENRE JOIN GENRE
ON(STREAM.CustomerId=CUSTOMER.CustomerId
AND STREAM.MovieId=MOVIE.MovieId
AND STREAM.MovieId=MOVIE_GENRE.MovieId
AND MOVIE_GENRE.GenreId=GENRE.GenreId)
WHERE (MOVIE.Duration<=120 AND  GENRE.Label='Biography')
AND CUSTOMER.CustomerId NOT IN
(SELECT CUSTOMER.CustomerId
FROM CUSTOMER JOIN COUNTRY JOIN REGION
ON(CUSTOMER.Country=COUNTRY.Name
AND COUNTRY.RegionId=REGION.RegionId)
WHERE REGION.Name='America');

/* EX 16 */
SELECT GENRE.Label, REGION.Name, 
SUM(CASE WHEN STREAM.MovieId=MOVIE.MovieId then 1 else 0 end) AS N
FROM GENRE JOIN MOVIE JOIN MOVIE_GENRE 
ON(MOVIE_GENRE.GenreId=GENRE.GenreId
AND MOVIE.MovieId=MOVIE_GENRE.MovieId),
STREAM JOIN CUSTOMER JOIN COUNTRY JOIN REGION
ON( STREAM.CustomerId=CUSTOMER.CustomerId
AND CUSTOMER.Country=COUNTRY.Name
AND COUNTRY.RegionId=REGION.RegionId)
GROUP BY GENRE.Label, REGION.Name
ORDER BY GENRE.Label, REGION.Name;
